[package]
name = "pgn-binpack"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
flate2 = "1.1.2"
human_bytes = "0.4.3"
pgn-reader = "0.28.0"
sfbinpack = "0.4.3"
shakmaty = "0.29.3"
walkdir = "2.5.0"
